/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.qlbh.ui;

import com.qlbh.utils.Chart;
import com.qlbh.utils.MsgBox;
import com.qlbh.utils.XImage;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author HAN-PC
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    private JButton btn_CheckClickMenu = new JButton();
    private int sizeBorder = 41;

    public home() {
        initComponents();
        btn_CheckClickMenu = btn_Home;
        showPanelMenu(pnl_Home);

        setLocationRelativeTo(null);
        this.setIconImage(XImage.getAppIcon());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        pnl_Acc = new javax.swing.JPanel();
        lbl_ImageUser = new javax.swing.JLabel();
        lbl_Role = new javax.swing.JLabel();
        lbl_ID = new javax.swing.JLabel();
        lbl_FullName = new javax.swing.JLabel();
        lbl_Email = new javax.swing.JLabel();
        pnl_Slide = new javax.swing.JPanel();
        btn_Dot1 = new javax.swing.JButton();
        btn_Dot2 = new javax.swing.JButton();
        btn_Dot3 = new javax.swing.JButton();
        btn_Dot4 = new javax.swing.JButton();
        btn_PrevSlide = new javax.swing.JButton();
        btn_NextSlide = new javax.swing.JButton();
        lbl_Slide1 = new javax.swing.JLabel();
        lbl_Slide2 = new javax.swing.JLabel();
        lbl_Slide3 = new javax.swing.JLabel();
        lbl_Slide4 = new javax.swing.JLabel();
        pnl_Menu = new javax.swing.JPanel();
        btn_Home = new javax.swing.JButton();
        btn_EmployeeManagement = new javax.swing.JButton();
        btn_CustomerManagement = new javax.swing.JButton();
        btn_AccountManagement = new javax.swing.JButton();
        btn_ShippingManagement = new javax.swing.JButton();
        btn_InventoryManagement = new javax.swing.JButton();
        btn_IntergradedManagement = new javax.swing.JButton();
        btn_OrderManagement = new javax.swing.JButton();
        btn_Account = new javax.swing.JButton();
        btn_Setting = new javax.swing.JButton();
        btn_LogOut = new javax.swing.JButton();
        btn_Exit = new javax.swing.JButton();
        pnl_Main = new javax.swing.JPanel();
        pnl_Home = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnl_IntergratedManagement = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cbo_IntergratedMana_chart = new javax.swing.JComboBox<>();
        cbo_IntergratedMana_year = new javax.swing.JComboBox<>();
        pnl_Intergrated_chart = new javax.swing.JPanel();
        pnl_OrderManagement = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel11 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel12 = new javax.swing.JPanel();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel13 = new javax.swing.JPanel();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SHOP MANAGEMENT");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        pnl_Acc.setBackground(new java.awt.Color(2, 16, 86));
        pnl_Acc.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 1, new java.awt.Color(0, 0, 0)));
        pnl_Acc.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lbl_ImageUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlbh/icon/home/user_120px.png"))); // NOI18N

        lbl_Role.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_Role.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Role.setText("EMPLOYEE");

        lbl_ID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_ID.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ID.setText("ID: NV001");

        lbl_FullName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_FullName.setForeground(new java.awt.Color(255, 255, 255));
        lbl_FullName.setText("FULLNAME: NGUYỄN VĂN TÈO");

        lbl_Email.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_Email.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Email.setText("EMAIL: teonv@gmail.com ");

        javax.swing.GroupLayout pnl_AccLayout = new javax.swing.GroupLayout(pnl_Acc);
        pnl_Acc.setLayout(pnl_AccLayout);
        pnl_AccLayout.setHorizontalGroup(
            pnl_AccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_AccLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lbl_ImageUser, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnl_AccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_AccLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pnl_AccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_FullName, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnl_AccLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lbl_Role, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_AccLayout.setVerticalGroup(
            pnl_AccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_AccLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pnl_AccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_ImageUser, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnl_AccLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(lbl_Role)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_ID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_FullName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_Email)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl_Slide.setBackground(new java.awt.Color(255, 255, 255));
        pnl_Slide.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 1, new java.awt.Color(0, 0, 0)));
        pnl_Slide.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Dot1.setBackground(new java.awt.Color(242, 242, 242));
        btn_Dot1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlbh/icon/home/new_moon_15px.png"))); // NOI18N
        btn_Dot1.setBorder(null);
        btn_Dot1.setBorderPainted(false);
        btn_Dot1.setContentAreaFilled(false);
        btn_Dot1.setFocusPainted(false);
        pnl_Slide.add(btn_Dot1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 150, -1, -1));

        btn_Dot2.setBackground(new java.awt.Color(242, 242, 242));
        btn_Dot2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlbh/icon/home/new_moon_15px.png"))); // NOI18N
        btn_Dot2.setBorder(null);
        btn_Dot2.setBorderPainted(false);
        btn_Dot2.setContentAreaFilled(false);
        btn_Dot2.setFocusPainted(false);
        pnl_Slide.add(btn_Dot2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 150, -1, -1));

        btn_Dot3.setBackground(new java.awt.Color(242, 242, 242));
        btn_Dot3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlbh/icon/home/new_moon_15px.png"))); // NOI18N
        btn_Dot3.setBorder(null);
        btn_Dot3.setBorderPainted(false);
        btn_Dot3.setContentAreaFilled(false);
        btn_Dot3.setFocusPainted(false);
        pnl_Slide.add(btn_Dot3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 150, -1, -1));

        btn_Dot4.setBackground(new java.awt.Color(242, 242, 242));
        btn_Dot4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlbh/icon/home/new_moon_gray_15px.png"))); // NOI18N
        btn_Dot4.setBorder(null);
        btn_Dot4.setBorderPainted(false);
        btn_Dot4.setContentAreaFilled(false);
        btn_Dot4.setFocusPainted(false);
        pnl_Slide.add(btn_Dot4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 150, -1, -1));

        btn_PrevSlide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlbh/icon/home/back_50px.png"))); // NOI18N
        btn_PrevSlide.setBorderPainted(false);
        btn_PrevSlide.setContentAreaFilled(false);
        btn_PrevSlide.setFocusPainted(false);
        pnl_Slide.add(btn_PrevSlide, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        btn_NextSlide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlbh/icon/home/forward_50px.png"))); // NOI18N
        btn_NextSlide.setBorderPainted(false);
        btn_NextSlide.setContentAreaFilled(false);
        btn_NextSlide.setFocusPainted(false);
        pnl_Slide.add(btn_NextSlide, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 70, -1, -1));

        lbl_Slide1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_Slide1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Slide1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlbh/icon/home/slide/slide0.jpg"))); // NOI18N
        pnl_Slide.add(lbl_Slide1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 190));

        lbl_Slide2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_Slide2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Slide2.setText("COMING SOON");
        pnl_Slide.add(lbl_Slide2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 190));

        lbl_Slide3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_Slide3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Slide3.setText("COMING SOON");
        pnl_Slide.add(lbl_Slide3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 190));

        lbl_Slide4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_Slide4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Slide4.setText("COMING SOON");
        pnl_Slide.add(lbl_Slide4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 190));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(pnl_Acc, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnl_Slide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnl_Acc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_Slide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pnl_Menu.setBackground(new java.awt.Color(255, 255, 255));
        pnl_Menu.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, new java.awt.Color(255, 204, 153)));
        pnl_Menu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btn_Home.setBackground(new java.awt.Color(56, 87, 245));
        btn_Home.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_Home.setForeground(new java.awt.Color(255, 255, 255));
        btn_Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlbh/icon/home/home_page_40px.png"))); // NOI18N
        btn_Home.setText("HOME PAGE");
        btn_Home.setAlignmentY(10.0F);
        btn_Home.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 41, 1, 1, new java.awt.Color(56, 87, 245)));
        btn_Home.setContentAreaFilled(false);
        btn_Home.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_Home.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_Home.setIconTextGap(28);
        btn_Home.setMargin(new java.awt.Insets(2, 40, 2, 14));
        btn_Home.setOpaque(true);
        btn_Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_HomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_HomeMouseExited(evt);
            }
        });
        btn_Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HomeActionPerformed(evt);
            }
        });

        btn_EmployeeManagement.setBackground(new java.awt.Color(2, 16, 86));
        btn_EmployeeManagement.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_EmployeeManagement.setForeground(new java.awt.Color(255, 255, 255));
        btn_EmployeeManagement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlbh/icon/home/valet_40px.png"))); // NOI18N
        btn_EmployeeManagement.setText("EMPLOYEE MANAGEMENT");
        btn_EmployeeManagement.setAlignmentY(10.0F);
        btn_EmployeeManagement.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 41, 1, 1, new java.awt.Color(2, 16, 86)));
        btn_EmployeeManagement.setContentAreaFilled(false);
        btn_EmployeeManagement.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_EmployeeManagement.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_EmployeeManagement.setIconTextGap(28);
        btn_EmployeeManagement.setMargin(new java.awt.Insets(2, 40, 2, 14));
        btn_EmployeeManagement.setOpaque(true);
        btn_EmployeeManagement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_EmployeeManagementMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_EmployeeManagementMouseExited(evt);
            }
        });
        btn_EmployeeManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EmployeeManagementActionPerformed(evt);
            }
        });

        btn_CustomerManagement.setBackground(new java.awt.Color(2, 16, 86));
        btn_CustomerManagement.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_CustomerManagement.setForeground(new java.awt.Color(255, 255, 255));
        btn_CustomerManagement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlbh/icon/home/reception_40px.png"))); // NOI18N
        btn_CustomerManagement.setText("CUSTOMER MANAGEMENT");
        btn_CustomerManagement.setAlignmentY(10.0F);
        btn_CustomerManagement.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 41, 1, 1, new java.awt.Color(2, 16, 86)));
        btn_CustomerManagement.setContentAreaFilled(false);
        btn_CustomerManagement.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_CustomerManagement.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_CustomerManagement.setIconTextGap(28);
        btn_CustomerManagement.setMargin(new java.awt.Insets(2, 40, 2, 14));
        btn_CustomerManagement.setOpaque(true);
        btn_CustomerManagement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_CustomerManagementMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_CustomerManagementMouseExited(evt);
            }
        });
        btn_CustomerManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CustomerManagementActionPerformed(evt);
            }
        });

        btn_AccountManagement.setBackground(new java.awt.Color(2, 16, 86));
        btn_AccountManagement.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_AccountManagement.setForeground(new java.awt.Color(255, 255, 255));
        btn_AccountManagement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlbh/icon/home/time_management_35px.png"))); // NOI18N
        btn_AccountManagement.setText("ACCOUNT MANAGEMENT");
        btn_AccountManagement.setAlignmentY(10.0F);
        btn_AccountManagement.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 41, 1, 1, new java.awt.Color(2, 16, 86)));
        btn_AccountManagement.setContentAreaFilled(false);
        btn_AccountManagement.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_AccountManagement.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_AccountManagement.setIconTextGap(33);
        btn_AccountManagement.setMargin(new java.awt.Insets(2, 40, 2, 14));
        btn_AccountManagement.setOpaque(true);
        btn_AccountManagement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_AccountManagementMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_AccountManagementMouseExited(evt);
            }
        });
        btn_AccountManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AccountManagementActionPerformed(evt);
            }
        });

        btn_ShippingManagement.setBackground(new java.awt.Color(2, 16, 86));
        btn_ShippingManagement.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_ShippingManagement.setForeground(new java.awt.Color(255, 255, 255));
        btn_ShippingManagement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlbh/icon/home/supplier_45px.png"))); // NOI18N
        btn_ShippingManagement.setText("SHIPPING MANAGEMENT");
        btn_ShippingManagement.setAlignmentY(10.0F);
        btn_ShippingManagement.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 40, 1, 1, new java.awt.Color(2, 16, 86)));
        btn_ShippingManagement.setContentAreaFilled(false);
        btn_ShippingManagement.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_ShippingManagement.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_ShippingManagement.setIconTextGap(25);
        btn_ShippingManagement.setMargin(new java.awt.Insets(2, 40, 2, 14));
        btn_ShippingManagement.setOpaque(true);
        btn_ShippingManagement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_ShippingManagementMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_ShippingManagementMouseExited(evt);
            }
        });
        btn_ShippingManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ShippingManagementActionPerformed(evt);
            }
        });

        btn_InventoryManagement.setBackground(new java.awt.Color(2, 16, 86));
        btn_InventoryManagement.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_InventoryManagement.setForeground(new java.awt.Color(255, 255, 255));
        btn_InventoryManagement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlbh/icon/home/warehouse_35px.png"))); // NOI18N
        btn_InventoryManagement.setText("INVENTORY MANAGEMENT");
        btn_InventoryManagement.setAlignmentY(10.0F);
        btn_InventoryManagement.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 43, 1, 1, new java.awt.Color(2, 16, 86)));
        btn_InventoryManagement.setContentAreaFilled(false);
        btn_InventoryManagement.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_InventoryManagement.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_InventoryManagement.setIconTextGap(31);
        btn_InventoryManagement.setMargin(new java.awt.Insets(2, 40, 2, 14));
        btn_InventoryManagement.setOpaque(true);
        btn_InventoryManagement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_InventoryManagementMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_InventoryManagementMouseExited(evt);
            }
        });
        btn_InventoryManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_InventoryManagementActionPerformed(evt);
            }
        });

        btn_IntergradedManagement.setBackground(new java.awt.Color(2, 16, 86));
        btn_IntergradedManagement.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_IntergradedManagement.setForeground(new java.awt.Color(255, 255, 255));
        btn_IntergradedManagement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlbh/icon/home/chart_45px.png"))); // NOI18N
        btn_IntergradedManagement.setText("INTERGRATED MANAGEMENT");
        btn_IntergradedManagement.setAlignmentY(10.0F);
        btn_IntergradedManagement.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 37, 1, 1, new java.awt.Color(2, 16, 86)));
        btn_IntergradedManagement.setContentAreaFilled(false);
        btn_IntergradedManagement.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_IntergradedManagement.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_IntergradedManagement.setIconTextGap(27);
        btn_IntergradedManagement.setMargin(new java.awt.Insets(2, 40, 2, 14));
        btn_IntergradedManagement.setOpaque(true);
        btn_IntergradedManagement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_IntergradedManagementMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_IntergradedManagementMouseExited(evt);
            }
        });
        btn_IntergradedManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_IntergradedManagementActionPerformed(evt);
            }
        });

        btn_OrderManagement.setBackground(new java.awt.Color(2, 16, 86));
        btn_OrderManagement.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_OrderManagement.setForeground(new java.awt.Color(255, 255, 255));
        btn_OrderManagement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlbh/icon/home/order_history_35px.png"))); // NOI18N
        btn_OrderManagement.setText("ORDER MANAGEMENT");
        btn_OrderManagement.setAlignmentY(10.0F);
        btn_OrderManagement.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 40, 1, 1, new java.awt.Color(2, 16, 86)));
        btn_OrderManagement.setContentAreaFilled(false);
        btn_OrderManagement.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_OrderManagement.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_OrderManagement.setIconTextGap(32);
        btn_OrderManagement.setMargin(new java.awt.Insets(2, 40, 2, 14));
        btn_OrderManagement.setOpaque(true);
        btn_OrderManagement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_OrderManagementMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_OrderManagementMouseExited(evt);
            }
        });
        btn_OrderManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_OrderManagementActionPerformed(evt);
            }
        });

        btn_Account.setBackground(new java.awt.Color(2, 16, 86));
        btn_Account.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_Account.setForeground(new java.awt.Color(255, 255, 255));
        btn_Account.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlbh/icon/home/account_35px.png"))); // NOI18N
        btn_Account.setText("ACCOUNT");
        btn_Account.setAlignmentY(10.0F);
        btn_Account.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 42, 1, 1, new java.awt.Color(2, 16, 86)));
        btn_Account.setContentAreaFilled(false);
        btn_Account.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_Account.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_Account.setIconTextGap(30);
        btn_Account.setMargin(new java.awt.Insets(2, 40, 2, 14));
        btn_Account.setOpaque(true);
        btn_Account.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_AccountMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_AccountMouseExited(evt);
            }
        });
        btn_Account.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AccountActionPerformed(evt);
            }
        });

        btn_Setting.setBackground(new java.awt.Color(2, 16, 86));
        btn_Setting.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_Setting.setForeground(new java.awt.Color(255, 255, 255));
        btn_Setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlbh/icon/home/settings_45px.png"))); // NOI18N
        btn_Setting.setText("SETTING");
        btn_Setting.setAlignmentY(10.0F);
        btn_Setting.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 35, 1, 1, new java.awt.Color(2, 16, 86)));
        btn_Setting.setContentAreaFilled(false);
        btn_Setting.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_Setting.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_Setting.setIconTextGap(27);
        btn_Setting.setMargin(new java.awt.Insets(2, 40, 2, 14));
        btn_Setting.setOpaque(true);
        btn_Setting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_SettingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_SettingMouseExited(evt);
            }
        });
        btn_Setting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SettingActionPerformed(evt);
            }
        });

        btn_LogOut.setBackground(new java.awt.Color(2, 16, 86));
        btn_LogOut.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_LogOut.setForeground(new java.awt.Color(255, 255, 255));
        btn_LogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlbh/icon/home/Logout_35px.png"))); // NOI18N
        btn_LogOut.setText("LOG OUT");
        btn_LogOut.setAlignmentY(10.0F);
        btn_LogOut.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 45, 1, 1, new java.awt.Color(2, 16, 86)));
        btn_LogOut.setContentAreaFilled(false);
        btn_LogOut.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_LogOut.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_LogOut.setIconTextGap(27);
        btn_LogOut.setMargin(new java.awt.Insets(2, 40, 2, 14));
        btn_LogOut.setOpaque(true);
        btn_LogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_LogOutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_LogOutMouseExited(evt);
            }
        });
        btn_LogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LogOutActionPerformed(evt);
            }
        });

        btn_Exit.setBackground(new java.awt.Color(2, 16, 86));
        btn_Exit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_Exit.setForeground(new java.awt.Color(255, 255, 255));
        btn_Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlbh/icon/home/shutdown_35px.png"))); // NOI18N
        btn_Exit.setText("EXIT");
        btn_Exit.setAlignmentY(10.0F);
        btn_Exit.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 42, 1, 1, new java.awt.Color(2, 16, 86)));
        btn_Exit.setContentAreaFilled(false);
        btn_Exit.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_Exit.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_Exit.setIconTextGap(29);
        btn_Exit.setMargin(new java.awt.Insets(2, 40, 2, 14));
        btn_Exit.setOpaque(true);
        btn_Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_ExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_ExitMouseExited(evt);
            }
        });
        btn_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_MenuLayout = new javax.swing.GroupLayout(pnl_Menu);
        pnl_Menu.setLayout(pnl_MenuLayout);
        pnl_MenuLayout.setHorizontalGroup(
            pnl_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_Home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_EmployeeManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_CustomerManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_AccountManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_ShippingManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_InventoryManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_IntergradedManagement, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
            .addComponent(btn_OrderManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_Account, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_Setting, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_LogOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_Exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnl_MenuLayout.setVerticalGroup(
            pnl_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_MenuLayout.createSequentialGroup()
                .addComponent(btn_Home, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btn_EmployeeManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btn_CustomerManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btn_AccountManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btn_ShippingManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btn_InventoryManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btn_IntergradedManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btn_OrderManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btn_Account, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btn_Setting, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btn_LogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btn_Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnl_Main.setBackground(new java.awt.Color(255, 255, 255));
        pnl_Main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_Home.setBackground(new java.awt.Color(255, 255, 255));
        pnl_Home.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));

        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"TIME WORK (8-16h)", null, null, null, null, null, null, null},
                {"SHIPPING", null, null, null, null, null, null, null},
                {"WAREHOUSE", null, null, null, null, null, null, null}
            },
            new String [] {
                "", "MONDAY", "TUESDAY", "WEDNESDAY", "THURSDAY", "FRIDAY", "SATURDAY", "SUNDAY"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.setName(""); // NOI18N
        jTable1.setRowHeight(121);
        jTable1.setSelectionBackground(new java.awt.Color(51, 153, 255));
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel2.setText("CALENDAR");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1270, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(570, 570, 570)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlbh/icon/home/notification_60px.png"))); // NOI18N
        jLabel1.setText("NOTIFICATION");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(154, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnl_HomeLayout = new javax.swing.GroupLayout(pnl_Home);
        pnl_Home.setLayout(pnl_HomeLayout);
        pnl_HomeLayout.setHorizontalGroup(
            pnl_HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnl_HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_HomeLayout.setVerticalGroup(
            pnl_HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_HomeLayout.createSequentialGroup()
                .addGap(0, 449, Short.MAX_VALUE)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnl_HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl_HomeLayout.createSequentialGroup()
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(216, Short.MAX_VALUE)))
        );

        pnl_Main.add(pnl_Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 670));

        pnl_IntergratedManagement.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("INTERGRATED MANAGEMENT");

        cbo_IntergratedMana_chart.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cbo_IntergratedMana_chart.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CHART", "LINECHART", "BARCHART", "PIECHART" }));
        cbo_IntergratedMana_chart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_IntergratedMana_chartActionPerformed(evt);
            }
        });

        cbo_IntergratedMana_year.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cbo_IntergratedMana_year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "YEAR", "2022", "2021", "2020", "2019", "2018", "2017" }));
        cbo_IntergratedMana_year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_IntergratedMana_yearActionPerformed(evt);
            }
        });

        pnl_Intergrated_chart.setBackground(new java.awt.Color(255, 255, 255));
        pnl_Intergrated_chart.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout pnl_IntergratedManagementLayout = new javax.swing.GroupLayout(pnl_IntergratedManagement);
        pnl_IntergratedManagement.setLayout(pnl_IntergratedManagementLayout);
        pnl_IntergratedManagementLayout.setHorizontalGroup(
            pnl_IntergratedManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_IntergratedManagementLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(pnl_Intergrated_chart, javax.swing.GroupLayout.PREFERRED_SIZE, 1236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_IntergratedManagementLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnl_IntergratedManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(pnl_IntergratedManagementLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(cbo_IntergratedMana_chart, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbo_IntergratedMana_year, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(445, 445, 445))
        );
        pnl_IntergratedManagementLayout.setVerticalGroup(
            pnl_IntergratedManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_IntergratedManagementLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_IntergratedManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbo_IntergratedMana_chart, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbo_IntergratedMana_year, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(pnl_Intergrated_chart, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pnl_Main.add(pnl_IntergratedManagement, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 670));

        jTabbedPane3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlbh/icon/Order/search_35px.png"))); // NOI18N
        jPanel8.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 40, 40));
        jPanel8.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 40));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Order By", "Item 2", "Item 3", "Item 4" }));

        jButton13.setText("ADD");

        jButton14.setText("DELETE");

        jButton15.setText("EDIT");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Order Management");

        jTable2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"ID001", "D123", "Mr.Duong", "SL3XL", "Lace underwear", "18/05/2022", "6", "50.000", "Pink color"},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Order ID", "Custtomer ID", "Customer Name", "Product ID", "Product Name", "Date", "Quantity", "Price", "Note"
            }
        ));
        jTable2.setRowHeight(30);
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(493, 493, 493)
                .addComponent(jLabel7)
                .addContainerGap(523, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox1))
                .addGap(18, 18, 18)
                .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane3.addTab("Order Management", jPanel11);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1270, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 638, Short.MAX_VALUE)
        );

        jTabbedPane3.addTab("Order Details", jPanel13);

        javax.swing.GroupLayout pnl_OrderManagementLayout = new javax.swing.GroupLayout(pnl_OrderManagement);
        pnl_OrderManagement.setLayout(pnl_OrderManagementLayout);
        pnl_OrderManagementLayout.setHorizontalGroup(
            pnl_OrderManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3)
        );
        pnl_OrderManagementLayout.setVerticalGroup(
            pnl_OrderManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_OrderManagementLayout.createSequentialGroup()
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnl_Main.add(pnl_OrderManagement, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 670));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pnl_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnl_Main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_Main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setColorMenuItem() {
        // set color button
        btn_Home.setBackground(new Color(2, 16, 86));
        btn_EmployeeManagement.setBackground(new Color(2, 16, 86));
        btn_CustomerManagement.setBackground(new Color(2, 16, 86));
        btn_AccountManagement.setBackground(new Color(2, 16, 86));
        btn_ShippingManagement.setBackground(new Color(2, 16, 86));
        btn_InventoryManagement.setBackground(new Color(2, 16, 86));
        btn_IntergradedManagement.setBackground(new Color(2, 16, 86));
        btn_OrderManagement.setBackground(new Color(2, 16, 86));
        btn_Account.setBackground(new Color(2, 16, 86));
        btn_Setting.setBackground(new Color(2, 16, 86));
        btn_LogOut.setBackground(new Color(2, 16, 86));
        btn_Exit.setBackground(new Color(2, 16, 86));
        this.btn_CheckClickMenu.setBackground(new Color(56, 87, 245));

        // set color border
        btn_Home.setBorder(BorderFactory.createMatteBorder(1, 41, 1, 1, new Color(2, 16, 86)));
        btn_EmployeeManagement.setBorder(BorderFactory.createMatteBorder(1, 41, 1, 1, new Color(2, 16, 86)));
        btn_CustomerManagement.setBorder(BorderFactory.createMatteBorder(1, 41, 1, 1, new Color(2, 16, 86)));
        btn_AccountManagement.setBorder(BorderFactory.createMatteBorder(1, 41, 1, 1, new Color(2, 16, 86)));
        btn_ShippingManagement.setBorder(BorderFactory.createMatteBorder(1, 40, 1, 1, new Color(2, 16, 86)));
        btn_InventoryManagement.setBorder(BorderFactory.createMatteBorder(1, 43, 1, 1, new Color(2, 16, 86)));
        btn_IntergradedManagement.setBorder(BorderFactory.createMatteBorder(1, 37, 1, 1, new Color(2, 16, 86)));
        btn_OrderManagement.setBorder(BorderFactory.createMatteBorder(1, 40, 1, 1, new Color(2, 16, 86)));
        btn_Account.setBorder(BorderFactory.createMatteBorder(1, 42, 1, 1, new Color(2, 16, 86)));
        btn_Setting.setBorder(BorderFactory.createMatteBorder(1, 35, 1, 1, new Color(2, 16, 86)));
        btn_LogOut.setBorder(BorderFactory.createMatteBorder(1, 45, 1, 1, new Color(2, 16, 86)));
        btn_Exit.setBorder(BorderFactory.createMatteBorder(1, 42, 1, 1, new Color(2, 16, 86)));
        this.btn_CheckClickMenu.setBorder(BorderFactory.createMatteBorder(1, sizeBorder, 1, 1, new Color(56, 87, 245)));

    }

    private void hoverMenu(JButton btn, int sizeMatteBorder) {
        setColorMenuItem();
        // set color button
        btn.setBackground(new Color(56, 87, 245));

        // set color border
        btn.setBorder(BorderFactory.createMatteBorder(1, sizeMatteBorder, 1, 1, new Color(56, 87, 245)));
    }

    private void showPanelMenu(JPanel pnl) {
        // Ẩn tất cả các form còn lại
        pnl_Home.setVisible(false);
        pnl_OrderManagement.setVisible(false);
        pnl_IntergratedManagement.setVisible(false);

        // show form lên khi click vào menu
        pnl.setVisible(true);
    }

    private void showChart() {
        if (cbo_IntergratedMana_chart.getSelectedIndex() != 0 && cbo_IntergratedMana_year.getSelectedIndex() != 0) {
            pnl_Intergrated_chart.removeAll();
            if (cbo_IntergratedMana_chart.getSelectedItem().equals("PIECHART")) {
                String[] element = {"JAN", "FEB", "MAR", "APR", "MAY", "JUN", "JUL", "AUG", "SEP", "OCT", "NOV", "DEC"};
                double[] percent = {5, 10, 4, 7, 2, 20, 7, 2, 13, 6, 10, 14};
                try {
                    pnl_Intergrated_chart.add(Chart.PieChart("REVENUE CHART", element, percent));
                } catch (Exception ex) {
                    Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else if (cbo_IntergratedMana_chart.getSelectedItem().equals("LINECHART")) {
                String[] element = {"JAN", "FEB", "MAR", "APR", "MAY", "JUN", "JUL", "AUG", "SEP", "OCT", "NOV", "DEC"};
                double[] value = {5, 20, 10, 30, 40, 70, 30, 50, 100, 70, 150, 200};
                try {
                    pnl_Intergrated_chart.add(Chart.LineChart("REVENUE CHART", "YEAR " + cbo_IntergratedMana_year.getSelectedItem(), "REVENUE", element, value));
                } catch (Exception ex) {
                    Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                String[] element = {"JAN", "FEB", "MAR", "APR", "MAY", "JUN", "JUL", "AUG", "SEP", "OCT", "NOV", "DEC"};
                double[] value = {5, 20, 10, 30, 40, 70, 30, 50, 100, 70, 150, 200};
                try {
                    pnl_Intergrated_chart.add(Chart.BarChart("REVENUE CHART", "YEAR " + cbo_IntergratedMana_year.getSelectedItem(), "REVENUE", element, value));
                } catch (Exception ex) {
                    Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            pnl_Intergrated_chart.validate();
        } else {
            pnl_Intergrated_chart.removeAll();
            showPanelMenu(pnl_IntergratedManagement);
        }
    }

    private void btn_HomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_HomeMouseEntered
        // TODO add your handling code here:
        hoverMenu(btn_Home, 41);
    }//GEN-LAST:event_btn_HomeMouseEntered

    private void btn_EmployeeManagementMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EmployeeManagementMouseEntered
        // TODO add your handling code here:
        hoverMenu(btn_EmployeeManagement, 41);
    }//GEN-LAST:event_btn_EmployeeManagementMouseEntered

    private void btn_CustomerManagementMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CustomerManagementMouseEntered
        // TODO add your handling code here:
        hoverMenu(btn_CustomerManagement, 41);
    }//GEN-LAST:event_btn_CustomerManagementMouseEntered

    private void btn_AccountManagementMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_AccountManagementMouseEntered
        // TODO add your handling code here:
        hoverMenu(btn_AccountManagement, 41);
    }//GEN-LAST:event_btn_AccountManagementMouseEntered

    private void btn_ShippingManagementMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ShippingManagementMouseEntered
        // TODO add your handling code here:
        hoverMenu(btn_ShippingManagement, 40);
    }//GEN-LAST:event_btn_ShippingManagementMouseEntered

    private void btn_InventoryManagementMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_InventoryManagementMouseEntered
        // TODO add your handling code here:
        hoverMenu(btn_InventoryManagement, 43);
    }//GEN-LAST:event_btn_InventoryManagementMouseEntered

    private void btn_IntergradedManagementMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_IntergradedManagementMouseEntered
        // TODO add your handling code here:
        hoverMenu(btn_IntergradedManagement, 37);
    }//GEN-LAST:event_btn_IntergradedManagementMouseEntered

    private void btn_OrderManagementMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_OrderManagementMouseEntered
        // TODO add your handling code here:
        hoverMenu(btn_OrderManagement, 40);
    }//GEN-LAST:event_btn_OrderManagementMouseEntered

    private void btn_AccountMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_AccountMouseEntered
        // TODO add your handling code here:
        hoverMenu(btn_Account, 42);
    }//GEN-LAST:event_btn_AccountMouseEntered

    private void btn_SettingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SettingMouseEntered
        // TODO add your handling code here:
        hoverMenu(btn_Setting, 35);
    }//GEN-LAST:event_btn_SettingMouseEntered

    private void btn_LogOutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_LogOutMouseEntered
        // TODO add your handling code here:
        hoverMenu(btn_LogOut, 45);
    }//GEN-LAST:event_btn_LogOutMouseEntered

    private void btn_ExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ExitMouseEntered
        // TODO add your handling code here:
        hoverMenu(btn_Exit, 42);
    }//GEN-LAST:event_btn_ExitMouseEntered

    private void btn_HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HomeActionPerformed
        // TODO add your handling code here:
        this.btn_CheckClickMenu = btn_Home;
        this.sizeBorder = 41;
        hoverMenu(btn_Home, 41);

        // code change Tab here
        showPanelMenu(pnl_Home);

    }//GEN-LAST:event_btn_HomeActionPerformed

    private void btn_EmployeeManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EmployeeManagementActionPerformed
        // TODO add your handling code here:
        this.btn_CheckClickMenu = btn_EmployeeManagement;
        this.sizeBorder = 41;
        hoverMenu(btn_EmployeeManagement, 41);

        // code change Tab here

    }//GEN-LAST:event_btn_EmployeeManagementActionPerformed

    private void btn_CustomerManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CustomerManagementActionPerformed
        // TODO add your handling code here:
        this.btn_CheckClickMenu = btn_CustomerManagement;
        this.sizeBorder = 41;
        hoverMenu(btn_CustomerManagement, 41);

        // code change Tab here

    }//GEN-LAST:event_btn_CustomerManagementActionPerformed

    private void btn_AccountManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AccountManagementActionPerformed
        // TODO add your handling code here:
        this.btn_CheckClickMenu = btn_AccountManagement;
        this.sizeBorder = 41;
        hoverMenu(btn_AccountManagement, 41);

        // code change Tab here

    }//GEN-LAST:event_btn_AccountManagementActionPerformed

    private void btn_ShippingManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ShippingManagementActionPerformed
        // TODO add your handling code here:
        this.btn_CheckClickMenu = btn_ShippingManagement;
        this.sizeBorder = 40;
        hoverMenu(btn_ShippingManagement, 40);

        // code change Tab here

    }//GEN-LAST:event_btn_ShippingManagementActionPerformed

    private void btn_InventoryManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_InventoryManagementActionPerformed
        // TODO add your handling code here:
        this.btn_CheckClickMenu = btn_InventoryManagement;
        this.sizeBorder = 43;
        hoverMenu(btn_InventoryManagement, 43);

        // code change Tab here

    }//GEN-LAST:event_btn_InventoryManagementActionPerformed

    private void btn_IntergradedManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_IntergradedManagementActionPerformed
        // TODO add your handling code here:
        this.btn_CheckClickMenu = btn_IntergradedManagement;
        this.sizeBorder = 37;
        hoverMenu(btn_IntergradedManagement, 37);

        // code change Tab here
        showPanelMenu(pnl_IntergratedManagement);
    }//GEN-LAST:event_btn_IntergradedManagementActionPerformed

    private void btn_OrderManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_OrderManagementActionPerformed
        // TODO add your handling code here:
        this.btn_CheckClickMenu = btn_OrderManagement;
        this.sizeBorder = 40;
        hoverMenu(btn_OrderManagement, 40);

        // code change Tab here
        showPanelMenu(pnl_OrderManagement);

    }//GEN-LAST:event_btn_OrderManagementActionPerformed

    private void btn_AccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AccountActionPerformed
        // TODO add your handling code here:
        this.btn_CheckClickMenu = btn_Account;
        this.sizeBorder = 42;
        hoverMenu(btn_Account, 42);

        // code change Tab here
    }//GEN-LAST:event_btn_AccountActionPerformed

    private void btn_SettingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SettingActionPerformed
        // TODO add your handling code here:
        this.btn_CheckClickMenu = btn_Setting;
        this.sizeBorder = 35;
        hoverMenu(btn_Setting, 35);

        // code change Tab here
    }//GEN-LAST:event_btn_SettingActionPerformed

    private void btn_LogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LogOutActionPerformed
        // TODO add your handling code here:
        // code change Tab here

    }//GEN-LAST:event_btn_LogOutActionPerformed

    private void btn_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ExitActionPerformed
        // TODO add your handling code here:
        // code change Tab here
        if (MsgBox.confirm(this, "Are you sure want to exit ?")) {
            System.exit(0);
        }
    }//GEN-LAST:event_btn_ExitActionPerformed

    private void btn_HomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_HomeMouseExited
        // TODO add your handling code here:
        setColorMenuItem();
    }//GEN-LAST:event_btn_HomeMouseExited

    private void btn_EmployeeManagementMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EmployeeManagementMouseExited
        // TODO add your handling code here:
        setColorMenuItem();
    }//GEN-LAST:event_btn_EmployeeManagementMouseExited

    private void btn_CustomerManagementMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CustomerManagementMouseExited
        // TODO add your handling code here:
        setColorMenuItem();
    }//GEN-LAST:event_btn_CustomerManagementMouseExited

    private void btn_AccountManagementMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_AccountManagementMouseExited
        // TODO add your handling code here:
        setColorMenuItem();
    }//GEN-LAST:event_btn_AccountManagementMouseExited

    private void btn_ShippingManagementMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ShippingManagementMouseExited
        // TODO add your handling code here:
        setColorMenuItem();
    }//GEN-LAST:event_btn_ShippingManagementMouseExited

    private void btn_InventoryManagementMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_InventoryManagementMouseExited
        // TODO add your handling code here:
        setColorMenuItem();
    }//GEN-LAST:event_btn_InventoryManagementMouseExited

    private void btn_IntergradedManagementMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_IntergradedManagementMouseExited
        // TODO add your handling code here:
        setColorMenuItem();
    }//GEN-LAST:event_btn_IntergradedManagementMouseExited

    private void btn_OrderManagementMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_OrderManagementMouseExited
        // TODO add your handling code here:
        setColorMenuItem();
    }//GEN-LAST:event_btn_OrderManagementMouseExited

    private void btn_AccountMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_AccountMouseExited
        // TODO add your handling code here:
        setColorMenuItem();
    }//GEN-LAST:event_btn_AccountMouseExited

    private void btn_SettingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SettingMouseExited
        // TODO add your handling code here:
        setColorMenuItem();
    }//GEN-LAST:event_btn_SettingMouseExited

    private void btn_LogOutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_LogOutMouseExited
        // TODO add your handling code here:
        setColorMenuItem();
    }//GEN-LAST:event_btn_LogOutMouseExited

    private void btn_ExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ExitMouseExited
        // TODO add your handling code here:
        setColorMenuItem();
    }//GEN-LAST:event_btn_ExitMouseExited

    private void cbo_IntergratedMana_chartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_IntergratedMana_chartActionPerformed
        // TODO add your handling code here:
        showChart();
    }//GEN-LAST:event_cbo_IntergratedMana_chartActionPerformed

    private void cbo_IntergratedMana_yearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_IntergratedMana_yearActionPerformed
        // TODO add your handling code here:
        showChart();
    }//GEN-LAST:event_cbo_IntergratedMana_yearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Account;
    private javax.swing.JButton btn_AccountManagement;
    private javax.swing.JButton btn_CustomerManagement;
    private javax.swing.JButton btn_Dot1;
    private javax.swing.JButton btn_Dot2;
    private javax.swing.JButton btn_Dot3;
    private javax.swing.JButton btn_Dot4;
    private javax.swing.JButton btn_EmployeeManagement;
    private javax.swing.JButton btn_Exit;
    private javax.swing.JButton btn_Home;
    private javax.swing.JButton btn_IntergradedManagement;
    private javax.swing.JButton btn_InventoryManagement;
    private javax.swing.JButton btn_LogOut;
    private javax.swing.JButton btn_NextSlide;
    private javax.swing.JButton btn_OrderManagement;
    private javax.swing.JButton btn_PrevSlide;
    private javax.swing.JButton btn_Setting;
    private javax.swing.JButton btn_ShippingManagement;
    private javax.swing.JComboBox<String> cbo_IntergratedMana_chart;
    private javax.swing.JComboBox<String> cbo_IntergratedMana_year;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lbl_Email;
    private javax.swing.JLabel lbl_FullName;
    private javax.swing.JLabel lbl_ID;
    private javax.swing.JLabel lbl_ImageUser;
    private javax.swing.JLabel lbl_Role;
    private javax.swing.JLabel lbl_Slide1;
    private javax.swing.JLabel lbl_Slide2;
    private javax.swing.JLabel lbl_Slide3;
    private javax.swing.JLabel lbl_Slide4;
    private javax.swing.JPanel pnl_Acc;
    private javax.swing.JPanel pnl_Home;
    private javax.swing.JPanel pnl_IntergratedManagement;
    private javax.swing.JPanel pnl_Intergrated_chart;
    private javax.swing.JPanel pnl_Main;
    private javax.swing.JPanel pnl_Menu;
    private javax.swing.JPanel pnl_OrderManagement;
    private javax.swing.JPanel pnl_Slide;
    // End of variables declaration//GEN-END:variables
}
